### PR TITLE
Fix issues relative to displaying datetimes in the results

### LINKED ISSUE #568: Update remaining time when displaying a scheduled result

### LINKED ISSUE #636: Show local time (not UTC)
The bug was reported by an user from Argentina. He mentioned the timestamp in the results but I guess it happens also in other places. Here is the email:

> Te adjunte una foto reciente. Aca en Argentina son las 19:12

### PR DESCRIPTION
**Pull request by Mariocj89**
Closes #568 
Closes #636

### CODE REVIEW

File: static/js/draw_manager.js [hunk 1]
```diff
@@ -337,9 +337,10 @@
 
             // Add the new result to the accordion
             var result_html =   '<p class="h3">' + this.options.msg_result +
-                                '       <small class="result-timestamp hidden-xs">' +
-                                '       ' + this.options.msg_generated_on + ' ' + result.datetime +
-                                '   </small>' +
+                                '<small class="result-timestamp">' +
+                                '   <span class="hidden-xs">' + this.options.msg_generated_on + '</span>' +
+                                '   <span class="relative-time" data-value="' + result.datetime + '">loading..</span>' +
```
Comment (dnaranjo89) [inline static/js/draw_manager.js]: string not translated
